on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

      - name: Format
        uses: astral-sh/ruff-action@f2e32211077f40bfeab40e16285216924ebea4cb # v2
        with:
          args: "format --check"

      - name: Lint
        uses: astral-sh/ruff-action@f2e32211077f40bfeab40e16285216924ebea4cb # v2

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Check lockfile
        run: uv lock --locked

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@36c6454b5a2348e7794ba2d82a21506605921e3d # v3

      - name: Run tests (ignoring test_bench.py as it requires GPU)
        run: |
          echo '# Code Coverage' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          uv run pytest --cov-report term --cov src >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
